-- MySQL Script generated by MySQL Workbench
-- Mon Aug 23 13:04:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `departmentID` INT NOT NULL,
  `departmentName` VARCHAR(45) NULL,
  PRIMARY KEY (`departmentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `employeesID` INT NOT NULL,
  `employeesName` VARCHAR(45) NULL,
  `employeesPosition` VARCHAR(45) NULL,
  `employeesDirecter` INT NULL,
  `employeesEntrydate` DATE NULL,
  `employeesPay` INT NULL,
  `employeesExtrapay` INT NULL,
  `departmentID` INT NOT NULL,
  PRIMARY KEY (`employeesID`, `departmentID`),
  INDEX `fk_employees_department_idx` (`departmentID` ASC) VISIBLE,
  CONSTRAINT `fk_employees_department`
    FOREIGN KEY (`departmentID`)
    REFERENCES `mydb`.`department` (`departmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
